trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  system.debug: true

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    goals: 'clean package -e -X'

- script: |
    echo "Listing target directory"
    ls -l target
    echo "Listing surefire reports"
    ls -l target/surefire-reports || echo "No surefire-reports folder"
  displayName: 'List test reports'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'JUnit Test Results'
    failTaskOnFailedTests: true
